version: '2.1'

services:
  smartdns:
    image: ubuntu:latest
    command: smartdns
    environment:
      LOG: '*'
    volumes:
      - ./build/smartdns:/bin/smartdns:ro
    networks:
      vpc:
        ipv4_address: 10.5.0.2

  debugger:
    image: ubuntu:latest
    command:
      - sleep
      - infinity
    volumes:
      - ./addons/docker-compose/resolv.conf:/etc/resolv.conf
    networks:
      - vpc
    depends_on:
      - smartdns

networks:
  vpc:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
